image: dpetrov/pyenv:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pyenv local 3.6.3

test:
  script:
    - tox

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
